DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
latch_xy_goal_tolerance: false

TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.05
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 1.0
  acc_lim_x: 0.2
  acc_lim_y: 0.2


  holonomic_robot: false
