# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5

  static_map: true
  rolling_window: true
  width: 50.0
  height: 50.0
  resolution: 0.1

